apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-reader
roleRef:
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: fabric8-metrics
  namespace: prometheus
userNames:
- system:serviceaccount:fabric8-metrics:prometheus