apiVersion: v1
kind: ConfigMap
metadata:
  name: forge
  annotations:
    fabric8.io/target-platform: "kubernetes"
    expose.config.fabric8.io/apiserver-url-key: apiserver.url
    #expose.service-key.config.fabric8.io/sso: keycloak.url
data:
  keycloak.url: http://f8tenant
  wit.url: http://wit
  apiserver.url: http://kubernetes
